[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python webhook_server.py"
healthcheckPath = "/"
restartPolicyType = "on_failure"
healthcheckTimeout = 600
healthcheckInterval = 30
healthcheckRetries = 3

[service]
port = 8000
