[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python webhook_server.py"
healthcheckPath = "/"
restartPolicyType = "always"
healthcheckTimeout = 300
healthcheckInterval = 60
healthcheckRetries = 5

[service]
port = 8000
