[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python webhook_server.py"
healthcheckPath = "/"
restartPolicy = "on_failure"
healthcheckTimeout = 30
healthcheckInterval = 300
healthcheckRetries = 3

[service]
port = 8080
